project_id = "qqrgwesxjqmdwxyxgipx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://qqrgwesxjqmdwxyxgipx.supabase.co"
additional_redirect_urls = ["http://localhost:3000/**", "https://*.lovable.app/**"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_sms_confirmations = false

[functions.shopify-api]
verify_jwt = false

[functions.promote-admin]
verify_jwt = false

[functions.send-custom-order]
verify_jwt = false

[functions.validate-referral]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false