// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqrgwesxjqmdwxyxgipx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcmd3ZXN4anFtZHd4eXhnaXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTI2MDcsImV4cCI6MjA3MjU4ODYwN30.NhxECb2AmlclQwNtyhfmBtPvsAZBwEm33Uogjx3FrR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});